name: Load Docker Images

on: 
  workflow_call:

jobs:
  start-services:
    runs-on: ubuntu-latest
    services:
        ldap:
          #  image: kwart/ldap-server
             image: rroemhild/test-openldap
             ports:
               - 10389:10389
               - 10636:10636
             credentials: 
               username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
               password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}
        sql-server:
          # Docker Hub image
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            MSSQL_PID: Express
            ACCEPT_EULA: Y
            SA_PASSWORD: Lucee!1433 # password must be complex or the service won't start
          ports:
            - 1433:1433
          options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5
        redis:
          # Docker Hub image
          image: redis
          # Set health checks to wait until redis has started
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            # Maps port 6379 on service container to the host
            - 6379:6379
          credentials: 
            username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}
        greenmail:
          image: greenmail/standalone:1.6.9
          ports:
            - 3025:3025 #SMTP
            - 3110:3110 #POP3
            - 3143:3143 #IMAP
            - 3465:3465 #SMTPS
            - 3993:3993 #IMAPS
            - 3995:3995 #POP3S
            - 8080:8080 #API
          credentials: 
            username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}
        mongo:
            image: mongo-express
            credentials: 
                username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}
        memcached:
            image: bitnami/memcached:latest
            credentials: 
                username: ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PUBLIC_TOKEN }}
    steps:
      - name: Docker Services loaded 
        run: echo "Docker Services loaded"