# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

env:
  MYSQL_PASSWORD: lucee
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: root

on: #[push, pull_request]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Lucee extensions
      uses: actions/cache@v2
      with:
        path: ~/work/Lucee/Lucee/cache/
        key: lucee-extensions
        restore-keys: lucee-extensions
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('loader/pom.xml','core/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE lucee' -u${{ env.MYSQL_ROOT_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
        mysql -e 'CREATE USER "lucee"@"localhost" IDENTIFIED BY "lucee";' -u${{ env.MYSQL_ROOT_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
        mysql -e 'GRANT ALL PRIVILEGES ON lucee.* TO "lucee"@"localhost"' -u${{ env.MYSQL_ROOT_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
    - name: Build with Ant
      run: ant -noinput -buildfile loader/build.xml
