name: Run OSV Scanner 

on: [workflow_dispatch]

jobs:
  scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.1"
    with:
      scan-args: |-
        --recursive
        --skip-git=true
        ./
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Lucee without using a Maven cache
      run: ant -noinput -buildfile loader/build.xml fast
    - name: Set up Go
      uses: actions/setup-go@v3
    - name: Install Google OSV Scanner
      run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
    - name: Run OSV vulnerabilities Scanner
      run: 'PATH="${PATH}:$(go env GOPATH)/bin" osv-scanner -r ${{ github.workspace }}'
    - name: Scan current project with grtype
      id: scan
      uses: anchore/scan-action@v3
      with:
        path: "."
    - name: output grtype report
      run: cat ${{ steps.scan.outputs.sarif }}
